version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-blog-project
permissions:
  - object: /home/ubuntu/django-blog-project
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/instance_os_dependencies.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/python_dependencies.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/gunicorn.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/nginx.sh
      timeout: 60
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: ubuntu
